<?xml version="1.0" ?>
<!DOCTYPE plugin [
<!ELEMENT plugin (doc?, attributes?, requires?, runtime?,
                  (extension-point|extension)*)>
<!ATTLIST plugin id         CDATA #REQUIRED>
<!ATTLIST plugin version    CDATA #REQUIRED>
<!ATTLIST plugin vendor     CDATA #IMPLIED>
<!ATTLIST plugin class      CDATA #IMPLIED>
<!ATTLIST plugin docs-path  CDATA #IMPLIED>

<!ELEMENT plugin-fragment (doc?, attributes?, requires?, runtime?,
                           (extension-point|extension)*)>
<!ATTLIST plugin-fragment id              CDATA #REQUIRED>
<!ATTLIST plugin-fragment version         CDATA #REQUIRED>
<!ATTLIST plugin-fragment vendor          CDATA #IMPLIED>
<!ATTLIST plugin-fragment plugin-id       CDATA #REQUIRED>
<!ATTLIST plugin-fragment plugin-version  CDATA #IMPLIED>
<!ATTLIST plugin-fragment match           (equal | equivalent | compatible
                                          | greater-or-equal) "compatible">
<!ATTLIST plugin-fragment docs-path       CDATA #IMPLIED>

<!ELEMENT attributes (attribute+)>

<!ELEMENT attribute (doc?, attribute*)>
<!ATTLIST attribute id     CDATA #REQUIRED>
<!ATTLIST attribute value  CDATA #IMPLIED>

<!ELEMENT doc (doc-ref*, doc-text?)>
<!ATTLIST doc caption  CDATA #IMPLIED>

<!ELEMENT doc-ref EMPTY>
<!ATTLIST doc-ref path     CDATA #REQUIRED>
<!ATTLIST doc-ref caption  CDATA #REQUIRED>

<!ELEMENT doc-text (#PCDATA)>

<!ELEMENT requires (import+)>

<!ELEMENT import (doc?)>
<!ATTLIST import id              CDATA #IMPLIED>
<!ATTLIST import plugin-id       CDATA #REQUIRED>
<!ATTLIST import plugin-version  CDATA #IMPLIED>
<!ATTLIST import match           (equal | equivalent | compatible
                                 | greater-or-equal) "compatible">
<!ATTLIST import exported        (true | false) "false">
<!ATTLIST import optional        (true | false) "false">
<!ATTLIST import reverse-lookup  (true | false) "false">

<!ELEMENT runtime (library+)>

<!ELEMENT library (doc?, export*)>
<!ATTLIST library id       CDATA #REQUIRED>
<!ATTLIST library path     CDATA #REQUIRED>
<!ATTLIST library type     (code | resources) #REQUIRED>
<!ATTLIST library version  CDATA #IMPLIED>

<!ELEMENT export EMPTY>
<!ATTLIST export prefix  CDATA #REQUIRED>

<!ELEMENT extension-point (doc?, parameter-def*)>
<!ATTLIST extension-point id                CDATA #REQUIRED>
<!ATTLIST extension-point parent-plugin-id  CDATA #IMPLIED>
<!ATTLIST extension-point parent-point-id   CDATA #IMPLIED>
<!ATTLIST extension-point extension-multiplicity  (any | one | one-per-plugin
                                                  | none) "any">

<!ELEMENT parameter-def (doc?, parameter-def*)>
<!ATTLIST parameter-def id             CDATA #REQUIRED>
<!ATTLIST parameter-def multiplicity   (one | any | none-or-one | one-or-more)
                                       "one">
<!ATTLIST parameter-def type           (string | boolean | number | date | time
                                       | date-time | null | any | plugin-id
									   | extension-point-id | extension-id
									   | fixed | resource) "string">
<!ATTLIST parameter-def custom-data    CDATA #IMPLIED>
<!ATTLIST parameter-def default-value  CDATA #IMPLIED>


<!ELEMENT extension (doc?, parameter*)>
<!ATTLIST extension plugin-id  CDATA #REQUIRED>
<!ATTLIST extension point-id   CDATA #REQUIRED>
<!ATTLIST extension id         CDATA #REQUIRED>

<!ELEMENT parameter (doc?, value?, parameter*)>
<!ATTLIST parameter id     CDATA #REQUIRED>
<!ATTLIST parameter value  CDATA #IMPLIED>

<!ELEMENT value (#PCDATA)>
]>

<plugin id="logicaldoc-audit" version="8.7.5" class="com.logicaldoc.audit.AuditPlugin">
	<requires>
		<import plugin-id="logicaldoc-core" />
		<import plugin-id="logicaldoc-enterprise-core" />
	</requires>
	
	<extension plugin-id="logicaldoc-core" point-id="DbInit" id="auditDbInit">
		<parameter id="position" value="1300" />
		<parameter id="name" value="logicaldoc-audit" />
		<parameter id="sqlFile" value="sql/logicaldoc-audit.sql" />
	</extension>

    <extension plugin-id="logicaldoc-enterprise-core" point-id="Cleaner" id="auditCleaner">
		<parameter id="class" value="com.logicaldoc.audit.AuditCleaner" />
		<parameter id="position" value="100" />
	</extension>
	
	<extension plugin-id="logicaldoc-core" point-id="Task" id="auditTask">
		<parameter id="name" value="Audit" />
	</extension>
	<extension plugin-id="logicaldoc-core" point-id="UserListener" id="userCreationListener">
		<parameter id="position" value="5" />
		<parameter id="class" value="com.logicaldoc.audit.AuditUser" />
	</extension>
	
    <extension plugin-id="logicaldoc-core" point-id="Feature" id="fau17">
	    <parameter id="name" value="Feature_17" />
    </extension>
</plugin>